int a = new Random().Next(1, 10);
Console.WriteLine(a);
int b = new Random().Next(1, 10);
Console.WriteLine(b);
int c = new Random().Next(1, 10);
Console.WriteLine(c);
int d = new Random().Next(1, 10);
Console.WriteLine(d);
int min = a;
int max = a;
if(a < min) min = a;
if(a > max) max = a;
if(b < min) min = b;  
if(b > max) max = b;
if(c < min) min = c;
if(c > max) max = c;
if(d < min) min = d;
if(d > max) max = d;
Console.Write("min = ");
Console.WriteLine(min);
Console.Write("max = ");
Console.WriteLine(max);